# Generated by Django 3.0.3 on 2020-03-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200330_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='test_id',
            field=models.CharField(blank=True, default='COV19', max_length=2000),
        ),
    ]
